name: Publish Docker image

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  build_image:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: '${{ env.DOCKERHUB_TAG }}:latest,${{ env.DOCKERHUB_TAG }}:${{ github.event.release.tag_name }}'
