name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        if: steps.check.outputs.changed == 'true'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        if: steps.check.outputs.changed == 'true'
        with:
          context: .
          push: true
          tags: unusualnorm/omnom:latest
